### ISSUE TITLE
Impossible to use your code!

### ISSUE THREAD

**Issue by boltlox** [codeneobee/kobra-neo-klipper-config#1]
Please, add gcode.cfg and calibration.cfg files, because Klipper throw error without them
<img width="1508" alt="Снимок экрана 2023-04-09 в 17 54 12" src="https://user-images.githubusercontent.com/14799152/230779966-19af9c1b-7f30-4a81-837c-5107fe0b690e.png">

**Comment by codeneobee** [comment]
The calibration.cfg is only a file with a few macros I use for calibration, it is not necessary so you can remove that line. According to your screenshot you should have the gcode.cfg already, it is a standard configuration file in Mainsail OS.
